sudo: false
services:
    - postgresql
addons:
    postgresql: "9.4"
language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
before_install:
    - eval $(curl https://travis-perl.github.io/init) --auto
